import { Menu, Transition } from '@headlessui/react'
import Head from 'next/head'
import Button from '../src/components/Button/Button'
import ButtonRowContainer from '../src/components/Button/ButtonRowContainer'
import HeaderVideo from '../src/components/Header/HeaderVideo'
import HorizontalList from '../src/components/HorizontalMovieList/HorizontalList'
import NavBar from '../src/components/NavBar/NavBar'
import React, { useState } from 'react';
import Youtube from './api/Youtube'
import SearchBar from '../src/components/SearchBar'
import axios from 'axios'

const dummycarditems = [
  { id: 1, name: 'title one', href: '#', current: true, src: '' },
  { id: 2, name: 'title two', href: '#', current: false, src: '' },
  { id: 3, name: 'title three', href: '#', current: false, src: '' },
  { id: 4, name: 'title four', href: '#', current: false, src: '' },
  { id: 5, name: 'title five', href: '#', current: false, src: '' },
  { id: 6, name: 'title six', href: '#', current: false, src: '' },
]


const defaultEndPoint = "https://rickandmortyapi.com/api/character/"
export async function getServerSideProps() {
  const res = await fetch(defaultEndPoint)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}
export default function Home({ data }) {
  const [search, setSearch] = useState('')
  const [video, setVideo] = useState([])


  // const playVideo = e => {
  //   e.target.play();
  //   setVideoStyles({
  //     transform: "scale(2, 2)",
  //     marginLeft: "300px"
  //   });
  // }
  // const stopVideo = e => {
  //   e.target.pause();
  //   setVideoStyles({
  //     transform: "scale(1, 1)",
  //     marginLeft: 0
  //   });
  // }



  // TODO add play and stopVideo to onMouseOver Events. 
  // TODO Intergrate Youtube API 
  // TODO Add search Context and Reducers. 
  const KEY = 'AIzaSyCBcL4D-cczyvr3WH8jgrPl5rtVcGhTymQ'

  
  const searchData = async (text) => {
    setSearch(text)
    const response = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: {
        part: 'snippet',
        q: search,
        maxResults: 15,
        key: KEY
      }
    })
    setVideo(response.data.items)
  }  

  console.log('videoState', video)
  
  
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black text-white">
        <NavBar />
        <HeaderVideo />
        <SearchBar search={searchData} />
        Found: {video.length}
        <HorizontalList data={video}/>
      </div>
    </div>
  )
}
