import Head from 'next/head';
import React, { useState } from 'react';
import prisma from '../lib/prisma';
import HeaderVideo from '../src/components/Header/HeaderVideo';
import HorizontalListDB from '../src/components/HorizontalMovieList/HorizontalListDB';
import HorizontalListYoutube from '../src/components/HorizontalMovieList/HorizontalListYoutube';
import NavBar from '../src/components/NavBar/NavBar';

// FETCH only Comedy Movies

// FETCH ALL Movies
export async function getStaticProps() {
	const movies = await prisma.movie.findMany({

	})
	const movielist = JSON.parse(JSON.stringify(movies))

	return {
		props: { movielist }
	}
}


export default function protectedRoute(props) {

	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-gradient-to-t from-black via-slate-900 to-slate-900 text-white scroll-smooth">
				<NavBar
				/>
				<HeaderVideo />
				<div>
					<HorizontalListDB data={props.movielist} category="Comedy" />
					<HorizontalListDB data={props.movielist} category="Fantasy" />
					<HorizontalListDB data={props.movielist} category="Animation" />
					<HorizontalListDB data={props.movielist} category="Action" />
				</div>
			</div>
		</div>
	)
}
